# Generated by Django 4.2 on 2023-05-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_users_groups_alter_users_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
