# Generated by Django 4.2 on 2023-05-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_users_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="blocked",
            field=models.BooleanField(default=False),
        ),
    ]
