# Generated by Django 4.2 on 2023-05-04 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("follows", "0001_initial"),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="users",
            field=models.ManyToManyField(
                related_name="books",
                through="follows.Follow",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
