# Generated by Django 4.2.1 on 2023-05-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='json_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdfs'),
        ),
    ]
