# Generated by Django 4.2.1 on 2023-05-09 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_json_data_book_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='json_data',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
        migrations.CreateModel(
            name='BookPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='books.book')),
            ],
        ),
    ]
