# Generated by Django 4.2.1 on 2023-05-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_json_data_remove_book_pdf_bookpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=10485760),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=10485760),
        ),
    ]
