# Generated by Django 4.2 on 2023-05-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0002_copy_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="copy",
            name="period_loan",
            field=models.IntegerField(default=7),
        ),
    ]
