# Generated by Django 4.2.1 on 2023-05-10 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0003_copy_period_loan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="copy",
            old_name="total_book",
            new_name="book_total_copies",
        ),
    ]
